name: go-randomy build
on: [push]
jobs:
  test:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, raspbian-private, macos-private]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - name: Test
        run: go test -v
  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bump version
        id: version_bump
        uses: anothrNick/github-tag-action@1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "master"
          WITH_V: true
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.version_bump.outputs.tag}}
          release_name: go-randomy ${{steps.version_bump.outputs.tag}}
          draft: false
          prerelease: false
