name: go-randomy build
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, raspbian-private, macos-private]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
        id: go
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: go test -v
  tag:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bump version
        if: github.ref == 'refs/heads/master'
        uses: anothrNick/github-tag-action@1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "master"
          WITH_V: true
